/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package certificate;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
//import static javax.mail.Transport.send;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import timetable.timetable;

/**
 *
 * @author mwinzi
 */
public class certificate extends javax.swing.JFrame {

    /**
     * Creates new form certificate
     */
    public certificate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabelcoursebiz = new javax.swing.JLabel();
        jComboBoxBisna = new javax.swing.JComboBox();
        jLabeltheo = new javax.swing.JLabel();
        jComboBoxtheo = new javax.swing.JComboBox();
        jLabelcoursesocio = new javax.swing.JLabel();
        jComboBoxsocial = new javax.swing.JComboBox();
        jLabelfaculty = new javax.swing.JLabel();
        jComboBoxBisna1 = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        jLabelday = new javax.swing.JLabel();
        jComboBoxday = new javax.swing.JComboBox();
        jLabeltime = new javax.swing.JLabel();
        jTextFieldtime = new javax.swing.JTextField();
        jLabelunitcode = new javax.swing.JLabel();
        jTextFieldlunitcode = new javax.swing.JTextField();
        jLabelname = new javax.swing.JLabel();
        jTextFieldunitname = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabelsem = new javax.swing.JLabel();
        jComboBoxsemester = new javax.swing.JComboBox();
        jLabellecsemail = new javax.swing.JLabel();
        jTextFieldlecsemail = new javax.swing.JTextField();
        jLabellecsname = new javax.swing.JLabel();
        jTextFieldlecsname = new javax.swing.JTextField();
        jLabelclassroom = new javax.swing.JLabel();
        jTextFieldclassroom = new javax.swing.JTextField();
        jButtonVIEW = new javax.swing.JButton();
        jButtonsave = new javax.swing.JButton();
        jButtoprint = new javax.swing.JButton();
        jButtonback = new javax.swing.JButton();
        jButtondelete = new javax.swing.JButton();
        jButtonexit = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanelpriny = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTabledip = new javax.swing.JTable();
        jLabelttt = new javax.swing.JLabel();
        jLabelyoow = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1400, 800));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("  ST.PAUL'S UNIVERSITY HORARIUM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 901, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );

        jScrollPane2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelcoursebiz.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelcoursebiz.setText("COURSES:");

        jComboBoxBisna.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jComboBoxBisna.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BUSINESS COMPUTER SCIENCE AND COMMUNICATION STUDIES", "Certificate in Business Management", "Information Technology", "Certificate in Communication", "Certificate in Computer Science" }));

        jLabeltheo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabeltheo.setText("COURSES:");

        jComboBoxtheo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jComboBoxtheo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "THEOLOGY", "Certificate in Theology", "Certificate in Music" }));

        jLabelcoursesocio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelcoursesocio.setText("COURSES:");

        jComboBoxsocial.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jComboBoxsocial.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SOCIAL SCIENCES", "Community Development and Social Work", "Criminology and Security Management", "Higher Education Instructional Design and Teaching" }));

        jLabelfaculty.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelfaculty.setText("FACULTY :");

        jComboBoxBisna1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jComboBoxBisna1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BUSINESS COMPUTER SCIENCE AND COMMUNICATION STUDIES", "THEOLOGY", "SOCIAL SCIENCES" }));
        jComboBoxBisna1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxBisna1ActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jLabelday.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelday.setText("DAY:");

        jComboBoxday.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBoxday.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MONDAY", "TUESDAY", "WEDNESDAY", "FRIDAY" }));

        jLabeltime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabeltime.setText("TIME:");

        jTextFieldtime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabelunitcode.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelunitcode.setText("UNIT CODE:");

        jTextFieldlunitcode.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabelname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelname.setText("NAME:");

        jTextFieldunitname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabelday)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabeltime)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldtime, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabelunitcode)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldlunitcode, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelname)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldunitname, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelday)
                    .addComponent(jComboBoxday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabeltime)
                    .addComponent(jTextFieldtime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelunitcode)
                    .addComponent(jTextFieldlunitcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelname)
                    .addComponent(jTextFieldunitname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jLabelsem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelsem.setText("SEMESTER:");

        jComboBoxsemester.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SEMESTER ONE", "SEMESTER TWO" }));

        jLabellecsemail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabellecsemail.setText("LECTURER'S EMAIL:");

        jTextFieldlecsemail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabellecsname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabellecsname.setText("NAME:");

        jTextFieldlecsname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabelclassroom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelclassroom.setText("CLASS ROOM:");

        jTextFieldclassroom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabellecsemail)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldlecsemail, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabelclassroom)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldclassroom, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabellecsname)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldlecsname, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabelsem)
                        .addGap(53, 53, 53)
                        .addComponent(jComboBoxsemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelsem)
                    .addComponent(jComboBoxsemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldlecsemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabellecsname)
                    .addComponent(jTextFieldlecsname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabellecsemail))
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelclassroom)
                    .addComponent(jTextFieldclassroom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(187, 187, 187))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelcoursebiz)
                                    .addComponent(jLabelfaculty))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxBisna1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxBisna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabelcoursesocio)
                                    .addGap(18, 18, 18)
                                    .addComponent(jComboBoxsocial, 0, 1, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabeltheo)
                                    .addGap(18, 18, 18)
                                    .addComponent(jComboBoxtheo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelfaculty)
                    .addComponent(jComboBoxBisna1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelcoursebiz)
                    .addComponent(jComboBoxBisna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabeltheo)
                    .addComponent(jComboBoxtheo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxsocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelcoursesocio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel3);

        jButtonVIEW.setBackground(new java.awt.Color(102, 0, 0));
        jButtonVIEW.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonVIEW.setText("VIEW");
        jButtonVIEW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVIEWActionPerformed(evt);
            }
        });

        jButtonsave.setBackground(new java.awt.Color(102, 0, 0));
        jButtonsave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonsave.setText("SAVE");
        jButtonsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsaveActionPerformed(evt);
            }
        });

        jButtoprint.setBackground(new java.awt.Color(102, 0, 0));
        jButtoprint.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtoprint.setText("PRINT");
        jButtoprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoprintActionPerformed(evt);
            }
        });

        jButtonback.setBackground(new java.awt.Color(102, 0, 0));
        jButtonback.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonback.setText("BACK");
        jButtonback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonbackActionPerformed(evt);
            }
        });

        jButtondelete.setBackground(new java.awt.Color(102, 0, 0));
        jButtondelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtondelete.setText("DELETE");
        jButtondelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtondeleteActionPerformed(evt);
            }
        });

        jButtonexit.setBackground(new java.awt.Color(102, 0, 0));
        jButtonexit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonexit.setText("EXIT");
        jButtonexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonexitActionPerformed(evt);
            }
        });

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jTabledip.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BUSINESS", "THEOLOGY", "SOCIAL_SCIENCES", "DAY", "TIME", "UNIT_CODE", "NAME", "SEMESTER", "EMAIL", "LECNAME", "CLASSROOM"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTabledip);

        jLabelttt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabelyoow.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanelprinyLayout = new javax.swing.GroupLayout(jPanelpriny);
        jPanelpriny.setLayout(jPanelprinyLayout);
        jPanelprinyLayout.setHorizontalGroup(
            jPanelprinyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelprinyLayout.createSequentialGroup()
                .addGroup(jPanelprinyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelprinyLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelprinyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelttt, javax.swing.GroupLayout.PREFERRED_SIZE, 918, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 899, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelprinyLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabelyoow, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanelprinyLayout.setVerticalGroup(
            jPanelprinyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelprinyLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabelyoow, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelttt, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
        );

        jScrollPane3.setViewportView(jPanelpriny);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jButtonVIEW)
                                .addGap(54, 54, 54)
                                .addComponent(jButtonsave)
                                .addGap(51, 51, 51)
                                .addComponent(jButtoprint)
                                .addGap(151, 151, 151)
                                .addComponent(jButtonback)
                                .addGap(36, 36, 36)
                                .addComponent(jButtondelete)
                                .addGap(36, 36, 36)
                                .addComponent(jButtonexit))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(285, 285, 285)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(907, 907, 907)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(49, 49, 49))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonVIEW)
                            .addComponent(jButtonsave)
                            .addComponent(jButtoprint)
                            .addComponent(jButtonback)
                            .addComponent(jButtondelete)
                            .addComponent(jButtonexit))
                        .addGap(26, 26, 26)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(686, 686, 686))
        );

        setSize(new java.awt.Dimension(1416, 839));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVIEWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVIEWActionPerformed

        DefaultTableModel Model= (DefaultTableModel) jTabledip.getModel();
        String FACULTY=(String)jComboBoxBisna1.getSelectedItem();
        String Semester=(String)jComboBoxsemester.getSelectedItem();
        jLabelttt.setText("");
        jLabelyoow.setText(
            "\nST PAUL'S UNIVERISTY  TIMETABLE\t\n" +jComboBoxsemester.getSelectedItem());
        jLabelttt.setText("FACULTY OF"   +jComboBoxBisna1.getSelectedItem());

        try{

            Class.forName("com.mysql.jdbc.Driver");
            Connection conn= DriverManager.getConnection("jdbc:mysql://localhost:3306/signdb","root","");
            Statement st=conn.createStatement();
            String query="SELECT * FROM certificate";
            ResultSet rs= st.executeQuery(query);

            while(rs.next()){

                String BUSINESS=rs.getString("BUSINESS");
                String THEOLOGY=rs.getString("THEOLOGY");
                String SOCIAL_SCIENCES=rs.getString("SOCIAL_SCIENCES");
                String DAY=rs.getString("DAY");
                String TIME=rs.getString("TIME");
                String UNIT_CODE=rs.getString("UNIT_CODE");
                String NAME=rs.getString("NAME");
                String SEMESTER=rs.getString("SEMESTER");
                String EMAIL=rs.getString("EMAIL");
                String LECNAME=rs.getString("LECNAME");
                String CLASSROOM=rs.getString("CLASSROOM");

                Model.addRow(new Object[]{BUSINESS,THEOLOGY,SOCIAL_SCIENCES,DAY,TIME,UNIT_CODE,NAME,SEMESTER,EMAIL,LECNAME,CLASSROOM});
            }

        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButtonVIEWActionPerformed

    private void jButtonsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsaveActionPerformed
        // TODO add your handling code here:

        String BUSINESS=(String)jComboBoxBisna.getSelectedItem();
        String THEOLOGY= (String)jComboBoxtheo.getSelectedItem();
        String SOCIAL_SCIENCES=(String)jComboBoxsocial.getSelectedItem();
        String DAY=(String)jComboBoxday.getSelectedItem();
        String TIME=jTextFieldtime.getText();
        String UNIT_CODE=jTextFieldlunitcode.getText();
        String NAME=jTextFieldunitname.getText();
        String SEMESTER=(String)jComboBoxsemester.getSelectedItem();
        String EMAIL=jTextFieldlecsemail.getText();
        String LECNAME=jTextFieldlecsname.getText();
        String CLASSROOM=jTextFieldclassroom.getText();

        try{

            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/signdb","root","");
            Statement st=conn.createStatement();
            st.executeUpdate("INSERT INTO certificate(BUSINESS,THEOLOGY,SOCIAL_SCIENCES,DAY,TIME,UNIT_CODE,NAME,SEMESTER,EMAIL,LECNAME,CLASSROOM)VALUES('"+BUSINESS+"','"+THEOLOGY+"','"+SOCIAL_SCIENCES+"','"+DAY+"','"+TIME+"','"+UNIT_CODE+"','"+NAME+"','"+SEMESTER+"','"+EMAIL+"','"+LECNAME+"','"+CLASSROOM+"')");
            JOptionPane.showMessageDialog(null,"SAVED");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_jButtonsaveActionPerformed

    private void jButtoprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoprintActionPerformed
        printerJob(jPanelpriny);

    }//GEN-LAST:event_jButtoprintActionPerformed

    private void jButtonbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonbackActionPerformed
        timetable itimetable= new timetable();
        itimetable.setVisible(true);
    }//GEN-LAST:event_jButtonbackActionPerformed

    private void jButtondeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtondeleteActionPerformed
        DefaultTableModel model =(DefaultTableModel) jTabledip.getModel();
        if(jTabledip.getSelectedRow()==-1){
            if(jTabledip.getSelectedRowCount()==0){

                JOptionPane.showMessageDialog(null, "no data to delete","ST PAULS UNIVERSITY HORARIUM",
                    JOptionPane.OK_OPTION);
            }else{
                JOptionPane.showMessageDialog(null, "select a row to delete","ST PAULS UNIVERSITY HORARIUM",
                    JOptionPane.OK_OPTION);
            }
        }else{
            model.removeRow(jTabledip.getSelectedRow());
        }
    }//GEN-LAST:event_jButtondeleteActionPerformed

    private void jButtonexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonexitActionPerformed
        frame = new JFrame("EXIT");
        if(JOptionPane.showConfirmDialog(frame,"DO YOU WANT TO EXIT","ST.PAUL'S HORARIUM",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jButtonexitActionPerformed

    private void jComboBoxBisna1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxBisna1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxBisna1ActionPerformed
    private JFrame frame;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(certificate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(certificate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(certificate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(certificate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new certificate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonVIEW;
    private javax.swing.JButton jButtonback;
    private javax.swing.JButton jButtondelete;
    private javax.swing.JButton jButtonexit;
    private javax.swing.JButton jButtonsave;
    private javax.swing.JButton jButtoprint;
    private javax.swing.JComboBox jComboBoxBisna;
    private javax.swing.JComboBox jComboBoxBisna1;
    private javax.swing.JComboBox jComboBoxday;
    private javax.swing.JComboBox jComboBoxsemester;
    private javax.swing.JComboBox jComboBoxsocial;
    private javax.swing.JComboBox jComboBoxtheo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelclassroom;
    private javax.swing.JLabel jLabelcoursebiz;
    private javax.swing.JLabel jLabelcoursesocio;
    private javax.swing.JLabel jLabelday;
    private javax.swing.JLabel jLabelfaculty;
    private javax.swing.JLabel jLabellecsemail;
    private javax.swing.JLabel jLabellecsname;
    private javax.swing.JLabel jLabelname;
    private javax.swing.JLabel jLabelsem;
    private javax.swing.JLabel jLabeltheo;
    private javax.swing.JLabel jLabeltime;
    private javax.swing.JLabel jLabelttt;
    private javax.swing.JLabel jLabelunitcode;
    private javax.swing.JLabel jLabelyoow;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelpriny;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTabledip;
    private javax.swing.JTextField jTextFieldclassroom;
    private javax.swing.JTextField jTextFieldlecsemail;
    private javax.swing.JTextField jTextFieldlecsname;
    private javax.swing.JTextField jTextFieldlunitcode;
    private javax.swing.JTextField jTextFieldtime;
    private javax.swing.JTextField jTextFieldunitname;
    // End of variables declaration//GEN-END:variables

private void printerJob(JPanel jPanelpriny) {
 
        PrinterJob printerJob = PrinterJob.getPrinterJob();
        printerJob.setJobName("Print record");
        
        printerJob.setPrintable(new Printable(){

            @Override
            public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
               
                if(pageIndex>0){
                return Printable.NO_SUCH_PAGE;
                }
                Graphics2D graphics2D= (Graphics2D)graphics;
                graphics2D.translate(pageFormat.getImageableX()*2, pageFormat.getImageableY()*2);
                
                graphics2D.scale(0.5,0.5);
                jPanelpriny.paint(graphics2D);
                return Printable.PAGE_EXISTS;
            }
        });

    boolean returningResult =printerJob.printDialog();
    if(returningResult){
    try{
    printerJob.print();
    }catch(PrinterException printerException ){
      JOptionPane.showMessageDialog(this, "Print error"+printerException.getMessage());
    }
    }
    }
}

