/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diploma;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.*;
//import static javax.mail.Transport.send;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import timetable.timetable;



/**
 *
 * @author mwinzi
 */
public class diploma extends javax.swing.JFrame {

    /**
     * Creates new form diploma
     */
    public diploma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtonsave = new javax.swing.JButton();
        jButtoprint = new javax.swing.JButton();
        jButtonback = new javax.swing.JButton();
        jButtonexit = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabelcoursebiz = new javax.swing.JLabel();
        jComboBoxBisna = new javax.swing.JComboBox();
        jLabeltheo = new javax.swing.JLabel();
        jComboBoxtheo = new javax.swing.JComboBox();
        jLabelcoursesocio = new javax.swing.JLabel();
        jComboBoxsocial = new javax.swing.JComboBox();
        jLabelfaculty = new javax.swing.JLabel();
        jComboBoxfaculty = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        jLabelday = new javax.swing.JLabel();
        jComboBoxday = new javax.swing.JComboBox();
        jLabeltime = new javax.swing.JLabel();
        jTextFieldtime = new javax.swing.JTextField();
        jLabelunitcode = new javax.swing.JLabel();
        jTextFieldlunitcode = new javax.swing.JTextField();
        jLabelname = new javax.swing.JLabel();
        jTextFieldunitname = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabelsem = new javax.swing.JLabel();
        jComboBoxsemester = new javax.swing.JComboBox();
        jLabellecsemail = new javax.swing.JLabel();
        jTextFieldlecsemail = new javax.swing.JTextField();
        jLabellecsname = new javax.swing.JLabel();
        jTextFieldlecsname = new javax.swing.JTextField();
        jLabelclassroom = new javax.swing.JLabel();
        jTextFieldclassroom = new javax.swing.JTextField();
        jLabelcoursehealth = new javax.swing.JLabel();
        jComboBoxhealth = new javax.swing.JComboBox();
        jButtonVIEW = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanelpriny = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTabledip = new javax.swing.JTable();
        jLabelttt = new javax.swing.JLabel();
        jLabelyoow = new javax.swing.JLabel();
        jButtondelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1400, 800));

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("  ST.PAUL'S UNIVERSITY HORARIUM");

        jButtonsave.setBackground(new java.awt.Color(102, 0, 0));
        jButtonsave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonsave.setText("SAVE");
        jButtonsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsaveActionPerformed(evt);
            }
        });

        jButtoprint.setBackground(new java.awt.Color(102, 0, 0));
        jButtoprint.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtoprint.setText("PRINT");
        jButtoprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoprintActionPerformed(evt);
            }
        });

        jButtonback.setBackground(new java.awt.Color(102, 0, 0));
        jButtonback.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonback.setText("BACK");
        jButtonback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonbackActionPerformed(evt);
            }
        });

        jButtonexit.setBackground(new java.awt.Color(102, 0, 0));
        jButtonexit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonexit.setText("EXIT");
        jButtonexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonexitActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(0));

        jLabelcoursebiz.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelcoursebiz.setText("BUSINESS:");

        jComboBoxBisna.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jComboBoxBisna.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BUSINESS COMPUTER SCIENCE AND COMMUNICATION STUDIES", "Diploma in Business Information Technology (DBIT)", "Diploma in Business Management", "Diploma in Computer Science", "Diploma in Communication", "Diploma in Film Production", "Diploma in Information Technology", "Diploma in Journalism", "Diploma in Public Relations" }));
        jComboBoxBisna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxBisnaActionPerformed(evt);
            }
        });

        jLabeltheo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabeltheo.setText("THEOLOGY:");

        jComboBoxtheo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jComboBoxtheo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "THEOLOGY", "Diploma in Music", "Diploma in Sign Language Interpretation", "Diploma in Theology", "N/A" }));

        jLabelcoursesocio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelcoursesocio.setText("SOCIAL_SCIENCES:");

        jComboBoxsocial.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jComboBoxsocial.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SOCIAL SCIENCES", "Diploma in Community Development", "Diploma in Counseling Psychology", "Diploma in Criminology and Security Management", "Diploma in Hotel and Catering Management", "Diploma in Leadership and Management", "Diploma in Peace Building and Conflict Resolution", "Diploma in Social Work", "Diploma in Education (Arts)", "Diploma in Education (Early Childhood Education)", "N/A" }));
        jComboBoxsocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxsocialActionPerformed(evt);
            }
        });

        jLabelfaculty.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelfaculty.setText("FACULTY :");

        jComboBoxfaculty.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jComboBoxfaculty.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BUSINESS COMPUTER SCIENCE AND COMMUNICATION STUDIES", "THEOLOGY", "SOCIAL SCIENCES", "HEALTH SCIENCES" }));

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder(0));

        jLabelday.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelday.setText("DAY:");

        jComboBoxday.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBoxday.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MONDAY", "TUESDAY", "WEDNESDAY", "FRIDAY" }));

        jLabeltime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabeltime.setText("TIME:");

        jTextFieldtime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabelunitcode.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelunitcode.setText("UNIT_CODE:");

        jTextFieldlunitcode.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldlunitcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldlunitcodeActionPerformed(evt);
            }
        });

        jLabelname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelname.setText("NAME:");

        jTextFieldunitname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabelday)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabeltime)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldtime, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabelunitcode)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldlunitcode, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelname)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldunitname, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelday)
                    .addComponent(jComboBoxday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabeltime)
                    .addComponent(jTextFieldtime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelunitcode)
                    .addComponent(jTextFieldlunitcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelname)
                    .addComponent(jTextFieldunitname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(0));

        jLabelsem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelsem.setText("SEMESTER:");

        jComboBoxsemester.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SEMESTER ONE", "SEMESTER TWO" }));

        jLabellecsemail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabellecsemail.setText(" EMAIL:");

        jTextFieldlecsemail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabellecsname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabellecsname.setText("LECNAME:");

        jTextFieldlecsname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabelclassroom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelclassroom.setText("CLASSROOM:");

        jTextFieldclassroom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabellecsemail)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldlecsemail, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabelclassroom)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldclassroom, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabellecsname)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldlecsname, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabelsem)
                        .addGap(53, 53, 53)
                        .addComponent(jComboBoxsemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelsem)
                    .addComponent(jComboBoxsemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldlecsemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabellecsname)
                    .addComponent(jTextFieldlecsname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabellecsemail))
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelclassroom)
                    .addComponent(jTextFieldclassroom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        jLabelcoursehealth.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelcoursehealth.setText("HEALTH_SCIENCES:");

        jComboBoxhealth.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jComboBoxhealth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Collage OF Health Sciences", "Diploma in Clinical Medicine and Surgery", "Diploma in Community Health and Development", "Diploma in Health Records Management and Informatics", "N/A" }));
        jComboBoxhealth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxhealthActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabeltheo)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxtheo, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelcoursebiz)
                            .addComponent(jLabelfaculty))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxfaculty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxBisna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabelcoursesocio)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxsocial, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabelcoursehealth)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxhealth, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(277, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelfaculty)
                    .addComponent(jComboBoxfaculty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelcoursebiz)
                    .addComponent(jComboBoxBisna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabeltheo)
                    .addComponent(jComboBoxtheo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelcoursesocio)
                    .addComponent(jComboBoxsocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelcoursehealth)
                    .addComponent(jComboBoxhealth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(423, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel3);

        jButtonVIEW.setBackground(new java.awt.Color(102, 0, 0));
        jButtonVIEW.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonVIEW.setText("VIEW");
        jButtonVIEW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVIEWActionPerformed(evt);
            }
        });

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jTabledip.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BUSINESS", "THEOLOGY", "SOCIAL_SCIENCES", "HEALTH_SCIENCES", "DAY", "TIME", "UNIT_CODE", "NAME", "SEMESTER", "EMAIL", "LECNAME", "CLASSROOM"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTabledip);

        jLabelttt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabelyoow.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanelprinyLayout = new javax.swing.GroupLayout(jPanelpriny);
        jPanelpriny.setLayout(jPanelprinyLayout);
        jPanelprinyLayout.setHorizontalGroup(
            jPanelprinyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelprinyLayout.createSequentialGroup()
                .addGroup(jPanelprinyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelprinyLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelprinyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelttt, javax.swing.GroupLayout.PREFERRED_SIZE, 918, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 899, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelprinyLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabelyoow, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanelprinyLayout.setVerticalGroup(
            jPanelprinyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelprinyLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabelyoow, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelttt, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 208, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
        );

        jScrollPane3.setViewportView(jPanelpriny);

        jButtondelete.setBackground(new java.awt.Color(102, 0, 0));
        jButtondelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtondelete.setText("DELETE");
        jButtondelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtondeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 901, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonVIEW)
                                .addGap(60, 60, 60)
                                .addComponent(jButtonsave)
                                .addGap(60, 60, 60)
                                .addComponent(jButtoprint)
                                .addGap(166, 166, 166)
                                .addComponent(jButtonback)
                                .addGap(78, 78, 78)
                                .addComponent(jButtondelete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonexit)
                                .addGap(27, 27, 27)))
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(591, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonVIEW)
                            .addComponent(jButtonsave)
                            .addComponent(jButtoprint)
                            .addComponent(jButtonback)
                            .addComponent(jButtondelete)
                            .addComponent(jButtonexit)))
                    .addComponent(jLabel4))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap(186, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonbackActionPerformed
       timetable itimetable= new timetable();
       itimetable.setVisible(true);
    }//GEN-LAST:event_jButtonbackActionPerformed
     private JFrame frame;
    private void jButtonexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonexitActionPerformed
      frame = new JFrame("EXIT"); 
      if(JOptionPane.showConfirmDialog(frame,"DO YOU WANT TO EXIT","ST.PAUL'S HORARIUM",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
      System.exit(0);
      }
    }//GEN-LAST:event_jButtonexitActionPerformed

    private void jComboBoxsocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxsocialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxsocialActionPerformed

    private void jComboBoxhealthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxhealthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxhealthActionPerformed

    private void jButtonVIEWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVIEWActionPerformed
        
        DefaultTableModel Model= (DefaultTableModel) jTabledip.getModel();
        String FACULTY=(String)jComboBoxfaculty.getSelectedItem();
        String Semester=(String)jComboBoxsemester.getSelectedItem();
        jLabelttt.setText("");
        jLabelyoow.setText(
        "\nST PAUL'S UNIVERISTY  TIMETABLE\t\n" +jComboBoxsemester.getSelectedItem());
          jLabelttt.setText("FACULTY OF"   +jComboBoxfaculty.getSelectedItem());
        
      try{
          
          Class.forName("com.mysql.jdbc.Driver");
          Connection conn= DriverManager.getConnection("jdbc:mysql://localhost:3306/signdb","root","");
          Statement st=conn.createStatement();
          String query="SELECT * FROM diploma";
          ResultSet rs= st.executeQuery(query);
          
          while(rs.next()){
              
          String BUSINESS=rs.getString("BUSINESS");
          String THEOLOGY=rs.getString("THEOLOGY");
          String SOCIAL_SCIENCES=rs.getString("SOCIAL_SCIENCES");
          String HEALTH_SCIENCES=rs.getString("HEALTH_SCIENCES");
          String DAY=rs.getString("DAY");
          String TIME=rs.getString("TIME");
          String UNIT_CODE=rs.getString("UNIT_CODE");
          String NAME=rs.getString("NAME");
          String SEMESTER=rs.getString("SEMESTER");
          String EMAIL=rs.getString("EMAIL");
          String LECNAME=rs.getString("LECNAME");
          String CLASSROOM=rs.getString("CLASSROOM");
    
          Model.addRow(new Object[]{BUSINESS,THEOLOGY,SOCIAL_SCIENCES,HEALTH_SCIENCES,DAY,TIME,UNIT_CODE,NAME,SEMESTER,EMAIL,LECNAME,CLASSROOM});
          }
  
      }catch(Exception e){
      JOptionPane.showMessageDialog(null,e);
      }
    }//GEN-LAST:event_jButtonVIEWActionPerformed

    private void jTextFieldlunitcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldlunitcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldlunitcodeActionPerformed

    private void jButtonsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsaveActionPerformed
        // TODO add your handling code here:
        
        String BUSINESS=(String)jComboBoxBisna.getSelectedItem();
        String THEOLOGY= (String)jComboBoxtheo.getSelectedItem();
        String SOCIAL_SCIENCES=(String)jComboBoxsocial.getSelectedItem();
        String HEALTH_SCIENCES=(String)jComboBoxhealth.getSelectedItem();
        String DAY=(String)jComboBoxday.getSelectedItem();
        String TIME=jTextFieldtime.getText();
        String UNIT_CODE=jTextFieldlunitcode.getText();   
        String NAME=jTextFieldunitname.getText();
        String SEMESTER=(String)jComboBoxsemester.getSelectedItem();
        String EMAIL=jTextFieldlecsemail.getText();
        String LECNAME=jTextFieldlecsname.getText();
        String CLASSROOM=jTextFieldclassroom.getText();
        
        
        try{
        
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/signdb","root","");        
            Statement st=conn.createStatement();
            st.executeUpdate("INSERT INTO diploma(BUSINESS,THEOLOGY,SOCIAL_SCIENCES,HEALTH_SCIENCES,DAY,TIME,UNIT_CODE,NAME,SEMESTER,EMAIL,LECNAME,CLASSROOM)VALUES('"+BUSINESS+"','"+THEOLOGY+"','"+SOCIAL_SCIENCES+"','"+HEALTH_SCIENCES+"','"+DAY+"','"+TIME+"','"+UNIT_CODE+"','"+NAME+"','"+SEMESTER+"','"+EMAIL+"','"+LECNAME+"','"+CLASSROOM+"')");
            JOptionPane.showMessageDialog(null,"SAVED");
        }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_jButtonsaveActionPerformed

    private void jComboBoxBisnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxBisnaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxBisnaActionPerformed

    private void jButtondeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtondeleteActionPerformed
     DefaultTableModel model =(DefaultTableModel) jTabledip.getModel();
       if(jTabledip.getSelectedRow()==-1){
            if(jTabledip.getSelectedRowCount()==0){
                
                JOptionPane.showMessageDialog(null, "no data to delete","ST PAUL'S UNIVERSITY HORARIUM",
                        JOptionPane.OK_OPTION);
            }else{
                JOptionPane.showMessageDialog(null, "select a row to delete","ST PAUL'S UNIVERSITY HORARIUM",
                        JOptionPane.OK_OPTION);
               }
        }else{
             model.removeRow(jTabledip.getSelectedRow());
           }
    }//GEN-LAST:event_jButtondeleteActionPerformed

    private void jButtoprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoprintActionPerformed
printerJob(jPanelpriny); 
            
           
    }//GEN-LAST:event_jButtoprintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(diploma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(diploma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(diploma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(diploma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new diploma().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonVIEW;
    private javax.swing.JButton jButtonback;
    private javax.swing.JButton jButtondelete;
    private javax.swing.JButton jButtonexit;
    private javax.swing.JButton jButtonsave;
    private javax.swing.JButton jButtoprint;
    private javax.swing.JComboBox jComboBoxBisna;
    private javax.swing.JComboBox jComboBoxday;
    private javax.swing.JComboBox jComboBoxfaculty;
    private javax.swing.JComboBox jComboBoxhealth;
    private javax.swing.JComboBox jComboBoxsemester;
    private javax.swing.JComboBox jComboBoxsocial;
    private javax.swing.JComboBox jComboBoxtheo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelclassroom;
    private javax.swing.JLabel jLabelcoursebiz;
    private javax.swing.JLabel jLabelcoursehealth;
    private javax.swing.JLabel jLabelcoursesocio;
    private javax.swing.JLabel jLabelday;
    private javax.swing.JLabel jLabelfaculty;
    private javax.swing.JLabel jLabellecsemail;
    private javax.swing.JLabel jLabellecsname;
    private javax.swing.JLabel jLabelname;
    private javax.swing.JLabel jLabelsem;
    private javax.swing.JLabel jLabeltheo;
    private javax.swing.JLabel jLabeltime;
    private javax.swing.JLabel jLabelttt;
    private javax.swing.JLabel jLabelunitcode;
    private javax.swing.JLabel jLabelyoow;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelpriny;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTabledip;
    private javax.swing.JTextField jTextFieldclassroom;
    private javax.swing.JTextField jTextFieldlecsemail;
    private javax.swing.JTextField jTextFieldlecsname;
    private javax.swing.JTextField jTextFieldlunitcode;
    private javax.swing.JTextField jTextFieldtime;
    private javax.swing.JTextField jTextFieldunitname;
    // End of variables declaration//GEN-END:variables

    private void printerJob(JPanel jPanelpriny) {
 
        PrinterJob printerJob = PrinterJob.getPrinterJob();
        printerJob.setJobName("Print record");
        
        printerJob.setPrintable(new Printable(){

            @Override
            public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
               
                if(pageIndex>0){
                return Printable.NO_SUCH_PAGE;
                }
                Graphics2D graphics2D= (Graphics2D)graphics;
                graphics2D.translate(pageFormat.getImageableX()*2, pageFormat.getImageableY()*2);
                
                graphics2D.scale(0.5,0.5);
                jPanelpriny.paint(graphics2D);
                return Printable.PAGE_EXISTS;
            }
        });

    boolean returningResult =printerJob.printDialog();
    if(returningResult){
    try{
    printerJob.print();
    }catch(PrinterException printerException ){
      JOptionPane.showMessageDialog(this, "Print error"+printerException.getMessage());
    }
    }
    }
}

