/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timetable;

import certificate.certificate;
import degree.degree;
import diploma.diploma;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import login.Login;
import masters.masters;
import phd.phd;

/**
 *
 * @author mwinzi
 */
public class timetable extends javax.swing.JFrame {

    /**
     * Creates new form timetable
     */
    public timetable() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jBtndip = new javax.swing.JButton();
        jbtncert = new javax.swing.JButton();
        jBtndegree = new javax.swing.JButton();
        jBtnmasters = new javax.swing.JButton();
        jBtnphd = new javax.swing.JButton();
        jButtonback = new javax.swing.JButton();
        jButtonexit = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1400, 800));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\mwinzi\\Desktop\\spu.png")); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\mwinzi\\Desktop\\spu.png")); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("  ST.PAUL'S UNIVERSITY HORARIUM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 966, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(153, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jBtndip.setBackground(new java.awt.Color(153, 153, 153));
        jBtndip.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtndip.setForeground(new java.awt.Color(255, 255, 255));
        jBtndip.setText("DIPLOMA");
        jBtndip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtndipActionPerformed(evt);
            }
        });

        jbtncert.setBackground(new java.awt.Color(153, 153, 153));
        jbtncert.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtncert.setForeground(new java.awt.Color(255, 255, 255));
        jbtncert.setText("CERTIFICATE");
        jbtncert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtncertActionPerformed(evt);
            }
        });

        jBtndegree.setBackground(new java.awt.Color(153, 153, 153));
        jBtndegree.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtndegree.setForeground(new java.awt.Color(255, 255, 255));
        jBtndegree.setText("DEGREE");
        jBtndegree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtndegreeActionPerformed(evt);
            }
        });

        jBtnmasters.setBackground(new java.awt.Color(153, 153, 153));
        jBtnmasters.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtnmasters.setForeground(new java.awt.Color(255, 255, 255));
        jBtnmasters.setText("MASTERS");
        jBtnmasters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnmastersActionPerformed(evt);
            }
        });

        jBtnphd.setBackground(new java.awt.Color(153, 153, 153));
        jBtnphd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtnphd.setForeground(new java.awt.Color(255, 255, 255));
        jBtnphd.setText("PhD");
        jBtnphd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnphdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtncert)
                .addGap(57, 57, 57)
                .addComponent(jBtndip)
                .addGap(48, 48, 48)
                .addComponent(jBtndegree)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jBtnmasters)
                .addGap(41, 41, 41)
                .addComponent(jBtnphd)
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtndip)
                    .addComponent(jbtncert)
                    .addComponent(jBtndegree)
                    .addComponent(jBtnmasters)
                    .addComponent(jBtnphd))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jButtonback.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonback.setText("BACK");
        jButtonback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonbackActionPerformed(evt);
            }
        });

        jButtonexit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonexit.setText("EXIT");
        jButtonexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonexitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jButtonback)
                        .addGap(318, 318, 318)
                        .addComponent(jButtonexit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, Short.MAX_VALUE))
                .addGap(601, 601, 601))
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonback)
                    .addComponent(jButtonexit))
                .addGap(47, 47, 47)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtncertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtncertActionPerformed
        certificate icertificate =new certificate();
        icertificate.setVisible(true);
    }//GEN-LAST:event_jbtncertActionPerformed

    private void jBtndipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtndipActionPerformed
       diploma idiploma = new diploma();
       idiploma.setVisible(true);
    }//GEN-LAST:event_jBtndipActionPerformed

    private void jBtndegreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtndegreeActionPerformed
        degree idegree= new degree();
        idegree.setVisible(true);
    }//GEN-LAST:event_jBtndegreeActionPerformed

    private void jBtnmastersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnmastersActionPerformed
        masters imasters= new masters();
        imasters.setVisible(true);
    }//GEN-LAST:event_jBtnmastersActionPerformed

    private void jBtnphdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnphdActionPerformed
        phd iphd = new phd();
        iphd.setVisible(true);
    }//GEN-LAST:event_jBtnphdActionPerformed

    private void jButtonbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonbackActionPerformed
        // TODO add your handling code here:
        Login iLogin=new Login();
        iLogin.setVisible(true);
    }//GEN-LAST:event_jButtonbackActionPerformed
    private   JFrame frame;
    private void jButtonexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonexitActionPerformed
        // TODO add your handling code here:
        frame=new JFrame("EXIT");
        
       if(JOptionPane.showConfirmDialog(frame,"DO YOU WANT TO EXIT?","ST.PAUL'S HORARIUM",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
           System.exit(0);
       }
    }//GEN-LAST:event_jButtonexitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(timetable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(timetable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(timetable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(timetable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new timetable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtndegree;
    private javax.swing.JButton jBtndip;
    private javax.swing.JButton jBtnmasters;
    private javax.swing.JButton jBtnphd;
    private javax.swing.JButton jButtonback;
    private javax.swing.JButton jButtonexit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtncert;
    // End of variables declaration//GEN-END:variables
}
